package ru.sashel007.quitsmoking.util;

public enum AppState {
    STARTING_PAGE,
    QUIT_DATE_SELECTION_PAGE,
    CIGARETTES_PER_DAY_PAGE,
    CIGARETTES_IN_PACK_PAGE,
    PACK_COST_PAGE,
    FIRST_MONTH_WITHOUT_SMOKING,
    NOTIFICATION_PAGE,
    SUBSEQUENT_LAUNCH
}
